#!/usr/bin/env python3
"""Generate uwp/xbb_version.generated.h from config/bitcoin-core.pin.

Run automatically from build-uwp.ps1; safe to re-run any time:
  ./scripts/generate-version-header.py

The header exposes the Bitcoin Core pin (not the MSIX package version).
Package version remains runtime Package.Current().Id.Version.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PIN = ROOT / "config" / "bitcoin-core.pin"
OUT = ROOT / "uwp" / "xbb_version.generated.h"


def parse_pin(path: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        data[k.strip()] = v.strip()
    return data


def main() -> int:
    if not PIN.is_file():
        print(f"error: missing {PIN}", file=sys.stderr)
        return 1
    pin = parse_pin(PIN)
    tag = pin.get("TAG", "")
    commit = pin.get("COMMIT", "")
    if not re.fullmatch(r"v[0-9]+(\.[0-9]+)*", tag):
        print(f"error: invalid TAG in pin: {tag!r}", file=sys.stderr)
        return 1
    if not re.fullmatch(r"[0-9a-f]{40}", commit):
        print(f"error: invalid COMMIT in pin: {commit!r}", file=sys.stderr)
        return 1

    display = tag.removeprefix("v")  # 31.1
    short = commit[:12]

    body = f"""// AUTO-GENERATED by scripts/generate-version-header.py — do not edit.
// Source: config/bitcoin-core.pin
#pragma once

// Bitcoin Core pin (product embed target). Not the MSIX package version.
#define XBB_CORE_TAG "{tag}"
#define XBB_CORE_TAG_DISPLAY "{display}"
#define XBB_CORE_COMMIT "{commit}"
#define XBB_CORE_COMMIT_SHORT "{short}"

// Convenience wide strings for XAML UI (UTF-16 literals).
#define XBB_CORE_TAG_W L"{tag}"
#define XBB_CORE_TAG_DISPLAY_W L"{display}"
"""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    old = OUT.read_text(encoding="utf-8") if OUT.is_file() else None
    if old == body:
        print(f"unchanged {OUT.relative_to(ROOT)} ({tag})")
        return 0
    OUT.write_text(body, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} Core={tag} commit={short}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
