// AUTO-GENERATED by scripts/generate-version-header.py — do not edit.
// Source: config/bitcoin-core.pin
#pragma once

// Bitcoin Core pin (product embed target). Not the MSIX package version.
#define XBB_CORE_TAG "v31.1"
#define XBB_CORE_TAG_DISPLAY "31.1"
#define XBB_CORE_COMMIT "9be056a8a72b624dae9623b2f7bded92c2a21c91"
#define XBB_CORE_COMMIT_SHORT "9be056a8a72b"

// Convenience wide strings for XAML UI (UTF-16 literals).
#define XBB_CORE_TAG_W L"v31.1"
#define XBB_CORE_TAG_DISPLAY_W L"31.1"
